In [1]:
#importing pandas - Pandas is a library which can handle all table and data related functions.. all the complete functions will be inported once we import pandas library
#short forming pandas as pd
#all the pandas functions are imported and stored in the memory
#In model creation, now we are in Data collection process stage
import pandas as pd

In [4]:
#assigning a variable dataset
#dataset variable reads the Salary data sheet
#panda helps to read the file
# In model create, this section is data preprocessing
dataset=pd.read_csv("Salary_Data.csv")

In [5]:
#executing the dataset to view what is stored in the dataset
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [9]:
#Assigning Independent to a input variable (independentv) from the dataset where the input data is present in the datatable.
#YearsExperience table givesonly the coulmn of data from the dataset variable
#after assigning the independent input variable, execute it
#If you want to assign more input columns then you can separate it by comma
#In model creation, this stage we are segregating inpyt, output fields
independentv=dataset[["YearsExperience"]]

In [11]:
#run the input/independentv variable to check whether that column from dataset loaded/stored correctly
independentv

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [12]:
#assigning output / dependent variable
#check wehter the dependentv variable is stored with correct Salary dataset
dependentv=dataset[["Salary"]]

In [14]:
dependentv

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [28]:
#In model creation, we are in splitting the input and output
#now we are using sklearn library and their function to split train set and test set
#calling out only the particular class->functions to avoid too much memory usage.
#If we call the particular class and function then only small memory is used whem importing the data usinf from function
#assigning test_test_split the train and test variables to store in the memory and also sizing will be done to consider the data till this sizing number (30%)
#range refers to the repeatable times to execute 
#underscore in the variable refers to the space in the variable name
#separate the train and test data to utilize the sklearn library
#give first train data, first test data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independentv, dependentv, test_size=0.30, random_state=0)

In [34]:
#using sk library use the function, and this sklearn library is for machine learning
#regressor is a variable and assigning with LinearRegression
#all the linearregression are all now stored in regressor
#first 2 lines are procedure
#give the LinearRegression values using the fit method for X_train and Y_train
#when it is running X_train and Y_train it creates the weight abd basis
#when the fit method runs then it means it created the model, we are in the model creation stage in this block
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [35]:
#to check the values in the model created for weight and bias, create and assign a variable using regressor coef_ function (y=wx+c, where w is weight)
weight=regressor.coef_
weight

array([[9360.26128619]])

In [38]:
#to check the values in the model created for weight and bias, create and assign a variable using regressor intercept function(y=wx+c, where w is weight)
bias=regressor.intercept_
bias

array([26777.3913412])

In [42]:
#Evaluation metrics stage
#validating the created model is correct or not
#create y_predict variable
#regressor is having all the values saved and so the calling the predict function to validate the X_test
#Evaluation needs to be done for test data so adding X_test
Y_pred=regressor.predict(X_test)

In [45]:
#Validating the metrics through RSquare method
#using the sklearn library call the r2_score function
#verify the Y-test output value and the Y-pred predicted value
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)

In [46]:
#running the r_score variable to check the R2 metrics value-cross checking
r_score

0.9740993407213511

In [ ]:
#we have got 0.9, as we know R2 is nearly to 1 is good model created and if it nearly to 0 then it is bad model
#with this score we have created a good model
#if the good model is created then we need to save the model and then we need to deploy it

In [49]:
#saving the model
#import pickle library to save the model
#create and save the file name
import pickle
filename="final_model_slr.sav"

In [52]:
#push the model in the file created
#before you run the code, check the folder whether this file is not created yet
#after running the code, check the folder whether this file is created
pickle.dump(regressor,open(filename, 'wb'))

In [70]:
#verify the the model is correctly saved
#provide the value to be predicted in the new result variable or we can give the years of experience through the input method to get the value from user
loaded_model=pickle.load(open("final_model_slr.sav", 'rb'))
num=int(input("Enter years of experience"))
result=loaded_model.predict([[num]])

Enter years of experience 18

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [71]:
#running the result variable for an input value of 18 as years of experience
result

array([[195262.09449268]])