In [1]:
import numpy as ny
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Social_Network_Ads - Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [5]:
independent=dataset[["User ID", "Age", "EstimatedSalary", "Gender_Male"]]
independent

      User ID  Age  EstimatedSalary  Gender_Male
0    15624510   19            19000            1
1    15810944   35            20000            1
2    15668575   26            43000            0
3    15603246   27            57000            0
4    15804002   19            76000            1
..        ...  ...              ...          ...
395  15691863   46            41000            0
396  15706071   51            23000            1
397  15654296   50            20000            0
398  15755018   36            33000            1
399  15594041   49            36000            0

[400 rows x 4 columns]

In [6]:
dependent=dataset[["Purchased"]]
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [7]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (independent, dependent, test_size=0.30, random_state=0)

In [9]:
from sklearn.svm import LinearSVC
classifier=LinearSVC()
classifier.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LinearSVC()

In [10]:
y_pred=classifier.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[77  2]
 [23 18]]

In [12]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.77      0.97      0.86        79
           1       0.90      0.44      0.59        41

    accuracy                           0.79       120
   macro avg       0.83      0.71      0.73       120
weighted avg       0.81      0.79      0.77       120

In [13]:
import pickle

In [16]:
filename='classification.sav'
pickle.dump(classifier,open(filename, 'wb'))
loaded_model=pickle.load(open('classification.sav', 'rb'))
result=loaded_model.predict([[21, 3000, 0, 1]])
result

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearSVC was fitted with feature names
  warnings.warn(

array([1])